- name: brew Install tenv, pre-commit, git-secrets, checkov.
  community.general.homebrew:
    name: tenv,pre-commit,git-secrets,checkov
    state: latest
    update_homebrew: true

- name: Install terraform and use.
  ansible.builtin.shell: tenv terraform install {{ terraform_tag }} && tenv terraform use {{ terraform_tag }}

- name: Install tflint.
  become: true
  ansible.builtin.shell:
    cmd: |
      TFLINT_VERSION={{ tflint_tag }}
      curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

- name: Fetch Trivy.
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
    return_content: true
  register: trivy_installer

- name: Install Trivy.
  become: true
  ansible.builtin.command:
    cmd: sh -s -- -b /usr/local/bin {{ trivy_tag }}
    stdin: "{{ trivy_installer.content }}"

- name: Install terraform-docs.
  become: true
  ansible.builtin.shell:
    chdir: /tmp
    cmd: |
      curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/{{ terraform_docs_tag }}/terraform-docs-{{ terraform_docs_tag }}-$(uname)-amd64.tar.gz
      tar -xzf terraform-docs.tar.gz
      chmod +x terraform-docs
      mv terraform-docs /usr/local/bin/terraform-docs

#- name: Create checkov command.
#  become: true
#  ansible.builtin.template:
#    src: ../template/command_checkov.sh.j2
#    dest: /usr/local/bin/checkov
#    mode: "0744"
