- name: brew Install goenv.
  community.general.homebrew:
    name: goenv
    state: latest
    update_homebrew: true

- name: Install go lang and use.
  ansible.builtin.shell: goenv install -s {{ golang_tag }} && goenv global {{ golang_tag }}

- name: Write the goenv command to the .bash_rc file.
  ansible.builtin.blockinfile:
    path: "{{ [ansible_user_dir, '.bashrc'] | path_join }}"
    marker: "# {mark} goenv. Written by Ansible."
    block: eval "$(goenv init -)"

- name: Install cue lang.
  ansible.builtin.shell: eval "$(goenv init -)" && go install cuelang.org/go/cmd/cue@{{ cuelang_tag }}
