- name: Write the cuelang command to the .bash_aliases file.
  ansible.builtin.blockinfile:
    path: "{{ [ansible_user_dir, '.bash_aliases'] | path_join }}"
    create: yes
    backup: yes
    marker: "# {mark} {{ item.name }}. Written by Ansible."
    block: "{{ item.block }}"
  loop:
    - name: cuelang
      block: |
        alias cue='docker run --rm cuelang/cue:{{ cuelang_tag }}'
